### ISSUE TITLE
P2P address is not updated even after the campaign status becomes funded

### ISSUE THREAD

**Issue by luckytokidoki** [skyl/free2z#1]
![address_not_updated](https://user-images.githubusercontent.com/77098373/156745019-d029b890-f3f0-4020-9f46-f255eaba1839.png)
P2P address not updated even after the campaign status becomes funded. Notice that I have saved my own address in the P2P field (above) but the page (below) still shows the F2Z address. Cheers!
![p2p_address_not_updated](https://user-images.githubusercontent.com/77098373/156745027-7ff27e08-e85d-4f63-84cc-ccf18bb7fcef.png)

**Comment by skyl** [comment]
absolutely correct! Thanks! Fixed now.

**Comment by skyl** [comment]
I wonder what browser you're using? My grid never breaks like in your pics

<img width="994" alt="Screen Shot 2022-03-04 at 2 30 06 AM" src="https://user-images.githubusercontent.com/61438/156747010-f1bf6439-5fa8-49cd-8263-eb463f55e2cd.png">

<img width="1482" alt="Screen Shot 2022-03-04 at 2 32 05 AM" src="https://user-images.githubusercontent.com/61438/156747484-07af3c72-eed9-4c80-9217-f2df65396dc6.png">


... ah, I think I see - you just have a bigger monitor than I do and like to browse large? I've mostly been concentrating on mobile portrait ... how's the UX with a XL window?

**Comment by luckytokidoki** [comment]
> I wonder what browser you're using?

I'm using the Brave browser [version 1.36.109 Chromium: 99.0.4844.51 (Official Build) (64-bit)](https://brave.com/latest/).

> how's the UX with a XL window?

The UX is quite good. I didn't any broken elements in the UI.

I think in general we need the docs/getting started article for newcomers though.

**Comment by skyl** [comment]
@luckytokidoki - here are the https://free2z.cash/docs - https://github.com/skyl/free2z/pull/3/files can probably merge that and easily update my deployment to pull from here. What do you think? It's a little messy with theme cruft ...
